# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_design/mb_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design || ORIG_REF_NAME==mb_design} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_buttons_1/mb_design_axi_gpio_buttons_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_buttons_1 || ORIG_REF_NAME==mb_design_axi_gpio_buttons_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_leds_0/mb_design_axi_gpio_leds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_leds_0 || ORIG_REF_NAME==mb_design_axi_gpio_leds_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_segments_1/mb_design_axi_gpio_segments_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_segments_1 || ORIG_REF_NAME==mb_design_axi_gpio_segments_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_switches_1/mb_design_axi_gpio_switches_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_switches_1 || ORIG_REF_NAME==mb_design_axi_gpio_switches_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_timer_0_1/mb_design_axi_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_timer_0_1 || ORIG_REF_NAME==mb_design_axi_timer_0_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_uartlite_0_1/mb_design_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_uartlite_0_1 || ORIG_REF_NAME==mb_design_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_clk_wiz_1_1/mb_design_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_clk_wiz_1_1 || ORIG_REF_NAME==mb_design_clk_wiz_1_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_mdm_1_1/mb_design_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_mdm_1_1 || ORIG_REF_NAME==mb_design_mdm_1_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_1/mb_design_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_1 || ORIG_REF_NAME==mb_design_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_axi_intc_1/mb_design_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mb_design_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_xbar_1/mb_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_xbar_1 || ORIG_REF_NAME==mb_design_xbar_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_axi_periph_1/mb_design_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_design_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_dlmb_v10_1/mb_design_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_dlmb_v10_1 || ORIG_REF_NAME==mb_design_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ilmb_v10_1/mb_design_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_ilmb_v10_1 || ORIG_REF_NAME==mb_design_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_dlmb_bram_if_cntlr_1/mb_design_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_design_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_1/mb_design_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_design_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_lmb_bram_1/mb_design_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_lmb_bram_1 || ORIG_REF_NAME==mb_design_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_xlconcat_1/mb_design_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_xlconcat_1 || ORIG_REF_NAME==mb_design_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_rst_clk_wiz_1_100M_1/mb_design_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_design_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_xlconstant_0_1/mb_design_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_xlconstant_0_1 || ORIG_REF_NAME==mb_design_xlconstant_0_1} -quiet] -quiet

# XDC: bd/mb_design/mb_design_ooc.xdc
