set_property SRC_FILE_INFO {cfile:C:/CR/projects/CustomPeriphDemo/CustomPeriphDemo.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc rfile:../../../CustomPeriphDemo.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports RGB1_Red]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports RGB1_Green]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports RGB1_Blue]
